### ISSUE TITLE
Undefined function or variable 'annealTempInput_Callback'.

### ISSUE THREAD

**Issue by aparente** [michaelswoody/MEMLET#4]
```
Undefined function or variable 'annealTempInput_Callback'.

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MEMLET (line 31)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MEMLET('annealTempInput_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
```

Changing the annealing temperature in the MEMLET Gui yields the error above. 

Adding the following line to MEMLET.m removes the error, but I'm not familiar with Matlab Gui's and am not sure if this sets the annealing temperature properly. 

`function annealTempInput_Callback(hObject, eventdata, handles)`

**Comment by michaelswoody** [comment]
Fixed in v1.3! Thanks for the report!
